/** Stable capability codes. Seeding adds missing capabilities without overwriting custom roles. */
export const permissionCodes = [
  'agenda.visualizar_propria',
  'agenda.visualizar_todas',
  'agenda.criar_propria',
  'agenda.criar_qualquer',
  'agenda.editar_propria',
  'agenda.editar_qualquer',
  'agenda.excluir_propria',
  'agenda.excluir_qualquer',
  'agenda.sobrepor',
  'agenda.gerenciar_disponibilidade',
  'clientes.visualizar_relacionados',
  'clientes.visualizar_todos',
  'clientes.criar',
  'clientes.editar',
  'clientes.excluir',
  'clientes.exportar',
  'atendimentos.iniciar_proprio',
  'atendimentos.iniciar_qualquer',
  'atendimentos.concluir_proprio',
  'atendimentos.concluir_qualquer',
  'atendimentos.registrar_consumo',
  'comandas.visualizar_proprias',
  'comandas.visualizar_todas',
  'comandas.abrir',
  'comandas.editar',
  'comandas.alterar_preco',
  'comandas.aplicar_desconto',
  'comandas.fechar',
  'comandas.cancelar',
  'comandas.corrigir_fechada',
  'servicos.visualizar',
  'servicos.criar',
  'servicos.editar',
  'servicos.desativar',
  'produtos.visualizar',
  'produtos.criar',
  'produtos.editar',
  'produtos.desativar',
  'produtos.visualizar_custo',
  'estoque.visualizar',
  'estoque.entrada',
  'estoque.ajustar',
  'estoque.registrar_perda',
  'estoque.baixa_manual',
  'estoque.permitir_negativo',
  'financeiro.visualizar',
  'financeiro.gerenciar',
  'caixa.gerenciar',
  'pagamentos.registrar',
  'pagamentos.estornar',
  'profissionais.gerenciar',
  'usuarios.gerenciar',
  'roles.gerenciar',
  'auditoria.visualizar',
  'configuracoes.gerenciar',
  'relatorios.financeiro',
  'relatorios.agenda',
  'relatorios.estoque',
] as const;
export const initialRoles: Record<string, { name: string; permissions: readonly string[] }> = {
  ROLE_ADMIN: { name: 'Administrador', permissions: permissionCodes },
  ROLE_ATENDENTE: {
    name: 'Atendente',
    permissions: [
      'agenda.visualizar_todas',
      'agenda.criar_qualquer',
      'agenda.editar_qualquer',
      'agenda.excluir_qualquer',
      'clientes.visualizar_todos',
      'clientes.criar',
      'clientes.editar',
      'comandas.visualizar_todas',
      'comandas.abrir',
      'comandas.editar',
      'produtos.visualizar',
      'produtos.criar',
      'estoque.visualizar',
      'estoque.entrada',
      'servicos.visualizar',
    ],
  },
  ROLE_PROFISSIONAL: {
    name: 'Profissional',
    permissions: [
      'agenda.visualizar_propria',
      'agenda.criar_propria',
      'agenda.editar_propria',
      'agenda.excluir_propria',
      'clientes.visualizar_relacionados',
      'atendimentos.iniciar_proprio',
      'atendimentos.concluir_proprio',
      'servicos.visualizar',
    ],
  },
};
